#!/bin/sh
# Since mangadesk stores its downloads relative to the working dir,
# we change dirs to the users home, assuring that the dir is writeable
# and our relative path forced in do_patch() makes sense.


show_help() {
	
	cat << _EOF
	[MANGADESK_DIR] mangadesk: [options] [arguments]


	Environment:

	MANGADESK_DIR=<wrkdir>
		As an alternative to the -d option, the directory from which
		Mangadesk will be executed can be specified via the variable
		MANGADESK_DIR.


	Options:

	-d 	<wrkdir>
		This specifies the directory from which mangadesk will be run.
		The passed dir overwrites the one inherited from the environment.

	-h
		Print this message.

	-v
		Print version information.


	Exit codes (of the wrapper script):

	0
		Everything worked as expected.

	1
		Invalid argument.

	2
		MANGADESK_DIR was empty, and so was HOME.

	3
		MANGADESK_DIR was not a directory.

_EOF

}


while getopts ":d:hv" opt; do

	case $opt in

		h)
			show_help
			exit 0
			;;

		v)
			echo __VERSION
			exit 0
			;;

		d)
			MANGADESK_DIR=$OPTARG
			;;

		:)
			echo "-$OPTARG requires a directory"
			exit 1
			;;

		\?)
			echo "Invalid option: -$OPTARG"
			show_help
			exit 1
			;;

	esac

done


if [ -z "$MANGADESK_DIR" ]; then

	if [ -n "$HOME" ]; then

		MANGADESK_DIR="$HOME"

	else

		exit 2

	fi

fi

if [ ! -d "$MANGADESK_DIR" ]; then

	echo "Directory $MANGADESK_DIR does not exist"
	exit 3

fi


cd "$MANGADESK_DIR"
exec /usr/libexec/mangadesk
exit 0
